import Head from "next/head";
import Link from "next/link";
import { Box, Spinner, Center, SimpleGrid } from "@chakra-ui/react";
import { useQuery } from "urql";
import Product from "../components/Product";
import Navbar from "../components/Navbar";
import { PRODUCT_QUERY } from "../lib/query";

export default function Home() {
	// fetch products from strapi
	const [results] = useQuery({ query: PRODUCT_QUERY });
	const { data, fetching, error } = results;

	if (fetching) {
		return (
			<Center h="100vh">
				<Spinner
					thickness="4px"
					speed="0.65s"
					emptyColor="gray.200"
					color="green.500"
					size="xl"
				/>
			</Center>
		);
	}
	if (error) return <p>{error.message}</p>;
	const products = data.products.data;
	console.log({ products });
	return (
		<div>
			{/* Head component allows adding metadata */}
			<Head>
				<title>Les Meubles</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box mt="28">
				<SimpleGrid minChildWidth="20rem" spacing="2rem">
					{products.map((product) => (
						<Product key={product.attributes.slug} product={product} />
					))}
				</SimpleGrid>
			</Box>
		</div>
	);
}
